export const soundMapConsonant = [
	{
		index: "1",
        letter: "p",
        word: "pear",
        mp3: "/audio/constant-p.mp3",
	},
	{
		index: "2",
        letter: "b",
        word: "bear",
        mp3: "/audio/constant-b.mp3",
	},
	{
		index: "3",
        letter: "f",
        word: "fan",
        mp3: "/audio/constant-f.mp3",
	},
	{
		index: "4",
        letter: "v",
        word: "van",
        mp3: "/audio/constant-v.mp3",
	},
	{
		index: "5",
        letter: "t",
        word: "top",
        mp3: "/audio/constant-t.mp3",
	},
	{
		index: "6",
        letter: "d",
        word: "dog",
        mp3: "/audio/constant-d.mp3",
	},
	{
		index: "7",
        letter: "k",
        word: "cat,kit",
        mp3: "/audio/constant-k.mp3",
	},
	{
		index: "8",
        letter: "g",
        word: "goat",
        mp3: "/audio/constant-g.mp3",
	},
	{
		index: "9",
        letter: "th",
        mp3: "/audio/constant-th-quiet.mp3",
	},
	{
		index: "10",
        letter: "TH",
        mp3: "/audio/constant-th-noisy.mp3",
	},
	{
		index: "11",
        letter: "s",
        mp3: "/audio/constant-s.mp3",
	},
	{
		index: "12",
        letter: "z",
        word: "zoo",
        mp3: "/audio/constant-z.mp3",
	},
	{
		index: "13",
        letter: "sh",
        mp3: "/audio/constant-sh.mp3",
	},
	{
		index: "14",
        letter: "su/zh/zu",
        word: "measure,seizure",
        mp3: "/audio/constant-zh.mp3",
	},
	{
		index: "15",
        letter: "ch",
        word: "chin",
        mp3: "/audio/constant-ch.mp3",
	},
	{
		index: "16",
        letter: "j",
        word: "jar",
        mp3: "/audio/constant-j.mp3",
	},
	{
		index: "17",
        letter: "m",
        mp3: "/audio/constant-m.mp3",
	},
	{
		index: "18",
        letter: "n",
        mp3: "/audio/constant-n.mp3",
	},
	{
		index: "19",
        letter: "ng",
        mp3: "/audio/constant-ng.mp3",
	},
	{
		index: "20",
        letter: "l",
        mp3: "/audio/constant-l.mp3",
	},
	{
		index: "21",
        letter: "r",
        mp3: "/audio/constant-r.mp3",
	},
	{
		index: "22",
        letter: "h",
        mp3: "/audio/constant-h.mp3",
	},
	{
		index: "23",
        letter: "w",
        mp3: "/audio/constant-w.mp3",
	},
];

export const soundMapVowel = [
	{
		index: "24",
        letter: "ee",
        word: "eel",
        mp3: "/audio/vowel-ee.mp3",
	},
	{
		index: "25",
        letter: "i",
        word: "it",
        mp3: "/audio/vowel-i.mp3",
	},
	{
		index: "26",
        letter: "e",
        word: "Ed",
        mp3: "/audio/vowel-e.mp3",
	},
	{
		index: "27",
        letter: "ae",
        word: "ate",
        mp3: "/audio/vowel-ae.mp3",
	},
	{
		index: "28",
        letter: "a",
        word: "at",
        mp3: "/audio/vowel-a.mp3",
	},
	{
		index: "29",
        letter: "u",
        word: "up",
        mp3: "/audio/vowel-u.mp3",
	},
	{
		index: "30",
        letter: "au/aw/o",
        word: "Bob",
        mp3: "/audio/vowel-au-aw-o.mp3",
	},
	{
		index: "31",
        letter: "oe",
        word: "toe",
        mp3: "/audio/vowel-oe.mp3",
	},
	{
		index: "32",
        letter: "uu",
        word: "foot",
        mp3: "/audio/vowel-uu.mp3",
	},
	{
		index: "33",
        letter: "oo",
        word: "boot",
        mp3: "/audio/vowel-oo.mp3",
	},
	{
		index: "34",
        letter: "ie",
        word: "ice",
        mp3: "/audio/vowel-ie.mp3",
	},
	{
		index: "35",
        letter: "ue",
        word: "use",
        mp3: "/audio/vowel-ue.mp3",
	},
	{
		index: "36",
        letter: "ou/ow",
        word: "out,owl",
        mp3: "/audio/vowel-ou-ow.mp3",
	},
	{
		index: "37",
        letter: "oi/oy",
        word: "oil,boy",
        mp3: "/audio/vowel-oi-oy.mp3",
	},
	{
		index: "38",
        letter: "er/ir/ur",
        word: "sir,her,fur",
        mp3: "/audio/vowel-er-ir-ur.mp3",
	},
	{
		index: "39",
        letter: "ar",
        word: "ark,car",
        mp3: "/audio/vowel-ar.mp3",
	},
	{
		index: "40",
        letter: "or",
        word: "ore,for",
        mp3: "/audio/vowel-or.mp3",
	},
];
